### ISSUE TITLE
./scripts/act-bootstrap.sh: function: not found

### ISSUE THREAD

**Issue by nakagit** [mnemonic-no/act-bootstrap#14]
Hi

When I run following command, I got the "function: not found" error message.
/opt/act-bootstrap# ./scripts/act-bootstrap.sh 1 http://localhost:8888
./scripts/act-bootstrap.sh: 5: ./scripts/act-bootstrap.sh: function: not found

Then I changed ./scripts/act-bootstrap.sh as following:
Line:1
(Before change) #!/bin/sh
(After change)  #!/bin/bash

And also I found a typo on ./scripts/act-bootstrap.sh as following:
Line:28
(Before change) mkdir ${LOGDIDR}
(After change)  mkdir ${LOGDIR}

Kind regards,
Yuki

**Comment by frbor** [comment]
Please update your repository again and rerun, as I've merged PR#15 linked above.

**Comment by nakagit** [comment]
Thanks a lot.  :)
